# -*- coding: utf-8 -*-
"""Fácil de 7. PCA ejercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZiEIodHCRQMG3dppOvKyFPB91Am0DtkQ

# Reconocimiento de Caras usando eigenfaces

El dataset usado en este proyecto es un dataset preprocesado obtenido desde "Labeled Faces in the Wild", aka LFW_:

  http://vis-www.cs.umass.edu/lfw/lfw-funneled.tgz (233MB)

El objetivo de este proyecto es, dada una imagen de un rostro famoso debe clasificarse como tal de forma correcta.

Por ejemplo, si introducimos una imagen del presidente Bush al sistema, este debe ser capaz de arrojar el resultado correcto.
"""

import sklearn

from time import time
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV
from sklearn.datasets import fetch_lfw_people
from sklearn.metrics import classification_report
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from scipy.stats import loguniform
#from sklearn.utils.fixes import loguniform

"""1. Obtenemos los datos, si no los tenemos en el disco, y los cargamos como arrays de numpy.


"""

lfw_people = fetch_lfw_people(min_faces_per_person=70, resize=0.4)

# sacamos las dimensiones de cada imagen y sus características
n_samples, h, w = lfw_people.images.shape

# obtenemos las características (features) en X
X = lfw_people.data
n_features = X.shape[1]

# etiquetas de las personas en y
y = lfw_people.target
target_names = lfw_people.target_names
n_classes = target_names.shape[0]

print("Tamaño total del dataset:")
print("n_samples: %d" % n_samples)
print("n_features: %d" % n_features)
print("n_classes: %d" % n_classes)

"""2. No olvides estandarizar los datos, ya que al ser imágenes es interesante que los valores sean entre 0 y 1 en lugar de entre 0 y 255.


"""

estandarizar = StandardScaler()
X_estandarizado = estandarizar.fit_transform(X)

"""3. Calculamos el PCA (eigenfaces) en el dataset (tratado como un dataset sin etiquetar): reducción de la dimensionalidad o extracción de características no supevisado.

Coge los 150 components más representativos y aplica la transformación al dataset.

Almacena la transformación en una variable llamada **X_pca**.
"""

n_components = 150
pca = PCA(n_components=n_components, svd_solver='randomized', whiten=True).fit(X_estandarizado)
X_pca = pca.transform(X_estandarizado)

print(X_pca.shape)
print(X_estandarizado.shape)

"""4. Mostramos los eigenfaces procedentes del PCA."""

eigenfaces = pca.components_.reshape((n_components, h, w))

plt.figure(figsize=(1.8 * 4, 2.4 * 4))
for i, eigenface in enumerate(eigenfaces):
    plt.subplot(10, 15, i + 1)
    plt.imshow(eigenface, cmap='gray')
    plt.xticks(())
    plt.yticks(())
plt.show()

#@title Consigue el Token para corregir el ejercicio en Nodd3r
import hashlib
correct = str(X_pca.shape)
pwd = hashlib.sha256(str(correct).encode())
if pwd.hexdigest() == '448e71289609e19c786e77be922d143df4f1bdee239fc05e077bcefe555dd187':
  print('El token para corregir en Nodd3r es:\n',pwd.hexdigest())
else:
  print('Parece que el PCA no lo has realizado bien. Vuelve a intentarlo')